stages:
  - build
  - deploy_dev
  - deploy_prod

variables:
  DOCKER_COMPOSE_FILE_DEV: "docker-compose.dev.yml"
  DOCKER_COMPOSE_FILE_PROD: "docker-compose.prod.yml"

# -------------------------------
# Build stage (frontend & backend)
# -------------------------------
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building frontend"
    - cd manas.ai && npm install && npm run build
    - echo "Building backend Docker image"
    - docker build -t searches_theallset_dev-api ./api.manas.ai
  artifacts:
    paths:
      - manas.ai/dist
    expire_in: 1 hour

# -------------------------------
# Deploy to DEV
# -------------------------------
deploy_dev:
  stage: deploy_dev
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEV_SERVER >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to DEV server"
    - scp -r ./api.manas.ai $DEV_SERVER:~/searches_theallset_dev/
    - scp -r ./manas.ai/dist $DEV_SERVER:~/searches_theallset_dev/manas.ai/
    - scp ./manas.ai/nginx.dev.conf $DEV_SERVER:~/searches_theallset_dev/manas.ai/
    - scp ./docker-compose.dev.yml $DEV_SERVER:~/searches_theallset_dev/
    - ssh $DEV_SERVER "cd ~/searches_theallset_dev && docker-compose -f docker-compose.dev.yml down && docker-compose -f docker-compose.dev.yml up -d"

# -------------------------------
# Deploy to PROD
# -------------------------------
deploy_prod:
  stage: deploy_prod
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $PROD_SERVER >> ~/.ssh/known_hosts
  script:
    - echo "Deploying to PROD server"
    - scp -r ./api.manas.ai $PROD_SERVER:~/searches_theallset/
    - scp -r ./manas.ai/dist $PROD_SERVER:~/searches_theallset/manas.ai/
    - scp ./manas.ai/nginx.prod.conf $PROD_SERVER:~/searches_theallset/manas.ai/
    - scp ./docker-compose.prod.yml $PROD_SERVER:~/searches_theallset/
    - ssh $PROD_SERVER "cd ~/searches_theallset && docker-compose -f docker-compose.prod.yml down && docker-compose -f docker-compose.prod.yml up -d"
  only:
    - main # Only deploy PROD from main branch
