version: "1.0"

services:
  api:
    build: ./api.manas.ai
    container_name: api
    env_file:
      - ./api.manas.ai/.env
    ports:
      - "5050:8000"
    networks:
      - manas-network

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./manas.ai/dist:/usr/share/nginx/html:ro
      - ./manas.ai/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - manas-network

# volumes:
# not needed since we’re using host bind mounts, but you can keep if you like
# certbot-etc:
# certbot-var:

networks:
  manas-network:
    driver: bridge
