version: "3.8"

services:
  api:
    build: ./api.manas.ai
    container_name: api
    env_file:
      - ./api.manas.ai/.env
    ports:
      - "5050:8000"
    networks:
      - manas-network

  frontend:
    image: nginx:alpine
    container_name: frontend
    volumes:
      - ./manas.ai/dist:/usr/share/nginx/html:ro
      - ./manas.ai/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot-etc:/etc/letsencrypt:ro
      - ./certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    networks:
      - manas-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./manas.ai/dist:/usr/share/nginx/html
    entrypoint: /bin/sh -c
    command: >
      trap exit TERM; while :; do
        certbot renew --webroot -w /usr/share/nginx/html;
        sleep 12h;
      done

# volumes:
# not needed since we’re using host bind mounts, but you can keep if you like
# certbot-etc:
# certbot-var:

networks:
  manas-network:
    driver: bridge
