const BASE_BACKEND_URL = import.meta.env.VITE_BASE_BACKEND_URL;
// const BASE_BACKEND_URL = "http://127.0.0.1:8000";
const WRITE_EMAIL_URL = import.meta.env.VITE_WRITE_EMAIL_URL;
const WRITE_SEARCH_URL = import.meta.env.VITE_WRITE_SEARCH_URL;

// Construct full URL
const WRITE_EMAIL_FULL_URL = `${BASE_BACKEND_URL}${WRITE_EMAIL_URL}`;
const WRITE_SEARCH_FULL_URL = `${BASE_BACKEND_URL}${WRITE_SEARCH_URL}`;

export { WRITE_EMAIL_FULL_URL, WRITE_SEARCH_FULL_URL };
