name: Mirror to GitLab

on:
  push:
    branches:
      - dev
      - main
      - prod

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to GitLab
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ secrets.GITLAB_REPO }}
          git push --mirror gitlab
